
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Wed Jan 07 16:25:30 EST 2004
//----------------------------------------------------

package lego.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_MOD = 12;
  public static final int T_COLON = 4;
  public static final int T_AND = 18;
  public static final int T_INT = 25;
  public static final int T_LSQBRACE = 6;
  public static final int T_OR = 19;
  public static final int T_NOT = 20;
  public static final int T_EQUIV = 22;
  public static final int T_MINUS = 9;
  public static final int T_GREATEREQ = 15;
  public static final int T_DIVIDE = 11;
  public static final int T_IDENTIFER = 26;
  public static final int T_RPAREN = 17;
  public static final int T_EXISTS = 24;
  public static final int T_EOF = 2;
  public static final int EOF = 0;
  public static final int T_TIMES = 10;
  public static final int T_GREATER = 14;
  public static final int T_RSQBRACE = 7;
  public static final int T_DOT = 5;
  public static final int T_IMPLIES = 21;
  public static final int error = 1;
  public static final int T_LPAREN = 16;
  public static final int T_EQ = 13;
  public static final int T_FORALL = 23;
  public static final int T_PLUS = 8;
  public static final int T_ERROR = 3;
}

